#include <stdio.h>
#include <stdlib.h>

long is_valid(char* input) {
    long w, x, y, z = 0;	
    w = input[0] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 15;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 13;
	y = y * x;
	z = z + y;
	w = input[1] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 10;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 16;
	y = y * x;
	z = z + y;
	w = input[2] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 12;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 2;
	y = y * x;
	z = z + y;
	w = input[3] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 10;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 8;
	y = y * x;
	z = z + y;
	w = input[4] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 14;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 11;
	y = y * x;
	z = z + y;
	w = input[5] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -11;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 6;
	y = y * x;
	z = z + y;
	w = input[6] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 10;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 12;
	y = y * x;
	z = z + y;
	w = input[7] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -16;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 2;
	y = y * x;
	z = z + y;
	w = input[8] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -9;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 2;
	y = y * x;
	z = z + y;
	w = input[9] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 1;
	x = x + 11;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 15;
	y = y * x;
	z = z + y;
	w = input[10] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -8;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 1;
	y = y * x;
	z = z + y;
	w = input[11] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -8;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 10;
	y = y * x;
	z = z + y;
	w = input[12] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -10;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 14;
	y = y * x;
	z = z + y;
	w = input[13] - '0';
	x = x * 0;
	x = x + z;
	x = x % 26;
	z = z / 26;
	x = x + -9;
	x = x == w ? 1 : 0;
	x = x == 0 ? 1 : 0;
	y = y * 0;
	y = y + 25;
	y = y * x;
	y = y + 1;
	z = z * y;
	y = y * 0;
	y = y + w;
	y = y + 10;
	y = y * x;
	z = z + y;
	return z;
}

int main() {
    char* s = malloc(15*sizeof(char));
    for (long i = 99999999999999; i >= 11111111111111; --i) {
        sprintf(s, "%ld", i);
        if (is_valid(s) == 0) {
            printf("Valid %s", s);
            return 0;
        } else if (i % 10000000 == 0) {
            printf("\n%ld", i);
        }
    }
    return 1;
}